default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: beer_swap_development

test:
  <<: *default
  database: beer_swap_test

production:
  <<: *default
  database: beer_swap_production
  username: beer_swap
  password: <%= ENV['BEER_SWAP_DATABASE_PASSWORD'] %>
